// <auto-generated />
using InfrastrcutureLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastrcutureLayer.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreLayer.Entites.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ALZaher_ELGiesh Street",
                            Email = "MohamedWaleedHassan12@gmail.com",
                            IsDeleted = false,
                            Name = "Mohamed Waleed Hassan",
                            PhoneNumber = "01095494490"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ALZaher_ELGiesh Street",
                            Email = "NewUser2@gmail.com",
                            IsDeleted = false,
                            Name = "NewUser2",
                            PhoneNumber = "01111112222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cairo",
                            Email = "NewUser3@gmail.com",
                            IsDeleted = false,
                            Name = "NewUser3",
                            PhoneNumber = "01111112222"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo",
                            Email = "NewUser4@gmail.com",
                            IsDeleted = false,
                            Name = "NewUser4",
                            PhoneNumber = "01111112222"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cairo",
                            Email = "NewUser5@gmail.com",
                            IsDeleted = false,
                            Name = "NewUser5",
                            PhoneNumber = "01111112222"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Cairo",
                            Email = "NewUser6@gmail.com",
                            IsDeleted = false,
                            Name = "NewUser6",
                            PhoneNumber = "01111112222"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
